networks:
  dokploy-network:
    external: true

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: blog
    ports:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1s
      retries: 60
      timeout: 5s
    networks:
      - dokploy-network
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000
    environment:
        DATABASE_URL: mysql://root:123@db:3306/blog
    networks:
        - dokploy-network

